#!/bin/bash
# Claude Code Format Hook - Auto-generated by /setup-format-hook
# PostToolUse hook: runs formatter/linter after Edit/Write
#
# Exit code rules: PostToolUse hook always exits 0
# - exit 2 causes UI to show "blocking error", misleading agent to retry or get stuck
# - Formatter/Linter runs silently, failure is non-blocking (|| true or 2>/dev/null)

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

# Check if file_path exists
if [ -z "$FILE_PATH" ] || [ ! -f "$FILE_PATH" ]; then
  exit 0
fi

# Get file extension
EXT="${FILE_PATH##*.}"

case "$EXT" in
  js|jsx|ts|tsx|mjs|cjs)
    npx prettier --write "$FILE_PATH" 2>/dev/null || true
    npx eslint --fix "$FILE_PATH" 2>/dev/null || true
    ;;

  json|jsonc)
    npx prettier --write "$FILE_PATH" 2>/dev/null || true
    ;;
esac

exit 0
